### ISSUE TITLE
Error stacktrace is not getting printed properly

### ISSUE THREAD

**Issue by antsmartian** [nodejs/repl#18]
Hello, 

I guess with this commit : https://github.com/nodejs/repl/commit/e06c75c8788c90b056c85d743cebea087d0cc98c

Error stacktrace is missing outside repl context too. For example, when I was working on this PR : https://github.com/nodejs/repl/pull/17

I noticed when assertions failed, the stack trace was missing. I saw only the below:

```
assert.js:269
    throw err;
    ^

AssertionError [ERR_ASSERTION]: should throw syntax error
    at 
```

**Comment by devsnek** [comment]
This was fixed in https://github.com/nodejs/repl/commit/f4f203e23a57c7ccf8c0dee703a1e14c983e1480
