### ISSUE TITLE
Standard autocomplete behavior

### ISSUE THREAD

**Issue by bogdan** [nodejs/repl#32]
I am a little surprised that `autocomplete` works differently from any other major implementation like Bash, ZSH etc.
The only way to use a suggested completion is press "right" key which is located to the side of the keyboard and requires a very inconvenient hand move.  

Don't you want <Tab> to really complete the expression when there is only one variant or otherwise list variants like in Bash?

**Comment by devsnek** [comment]
totally agree, feel free to send a pr.

**Comment by devsnek** [comment]
I updated <kbd>Tab</kbd> to show a list instead of cycling the inline completion. Next on my list is jumping on completions like `P` will jump to `Pro` for `Promise` and `Proxy`.

**Comment by caub** [comment]
There's some bug if you press space at the middle of the completion

![repl-bug-complete-space](https://user-images.githubusercontent.com/3134574/61577860-82cdb080-aaed-11e9-8dac-ea2eceeb4909.gif)
