### ISSUE TITLE
repl Ctrl-r keybinding to search history

### ISSUE THREAD

**Issue by vapniks** [nodejs/repl#34]
Most repl's I've used before allow you to quickly get a previous command back by using the Ctrl+r key to search the command history. It makes life so much easier when you're testing stuff out. Any chance this could be implemented for the nodejs repl?

**Comment by DanielFGray** [comment]
To piggy back on this idea, in bash and zsh I have a bind on Ctrl-r to show my history in [fzf](https://github.com/junegunn/fzf), it would be great if there was some kind of mechanism to provide re-maps (prehaps maybe some kind of `.nodereplrc.js`?)
