### ISSUE TITLE
Issues with Number.MIN_VALUE 

### ISSUE THREAD

**Issue by TomLavenziano** [nodejs/repl#39]
### Expected behavior
Directly evaluating `Number.MIN_VALUE` should return the value `5e-324`.
Operating on `Number.MIN_VALUE` should return the correct result.

### Actual behavior
Directly evaluating `Number.MIN_VALUE` instantly kills / exits the REPL process. No stacktrace or output is printed. This only occurs when evaluated directly, ie. `console.log(Number.MIN_VALUE)` prints correctly without exiting.

The automatic evaluation that prints as a comment on the same line before pressing enter still displays correctly (`> Number.MIN_VALUE // 5e-324`).

Performing addition, subtraction, and division operations on `Number.MIN_VALUE` returns incorrect results. Performing multiplication on `Number.MIN_VALUE` causes the REPL process to exit as well.

Concatenating a string with `Number.MIN_VALUE` _does_ return the correct result without exiting.

This behavior only occurs with `Number.MIN_VALUE`, evaluating and operating on `Number.MAX_VALUE` returns correctly.

### Steps to reproduce

Exit on evaluation:
```bash
$ node-prototype-repl
Node.js v12.8.1 (V8 7.5.288.22-node.16)
Prototype REPL - https://github.com/nodejs/repl
> Number.MIN_VALUE // 5e-324

$
```

Incorrect arithmetic results and exiting on multiplication:
```bash
$ node-prototype-repl
Node.js v12.8.1 (V8 7.5.288.22-node.16)
Prototype REPL - https://github.com/nodejs/repl
> Number.MIN_VALUE + 100 // 100
100
> Number.MIN_VALUE - 100 // -100
-100
> Number.MIN_VALUE / 100 // 0
0
> Number.MIN_VALUE * 100 // 4.94e-322

$
```

Correct evaluation when concatenating with a string:
```bash
$ node-prototype-repl
Node.js v12.8.1 (V8 7.5.288.22-node.16)
Prototype REPL - https://github.com/nodejs/repl
> Number.MIN_VALUE + 'Test' // '5e-324Test'
'5e-324Test'

```

**Comment by devsnek** [comment]
i can't reproduce the immediate exits. The arithmetic you posted is correct though
