### ISSUE TITLE
Multi-line input not possible

### ISSUE THREAD

**Issue by bdcarr** [nodejs/repl#40]
Hi guys, I often use the node REPL to analyse objects/arrays I've logged. In the mainline REPL, I just paste em in and it seems to detect when a line isn't complete:
![image](https://user-images.githubusercontent.com/1940488/67061565-74566a00-f1ac-11e9-8fc0-569ccffac213.png)

With the prototype REPL, it automatically executes each line:
![image](https://user-images.githubusercontent.com/1940488/67061625-9354fc00-f1ac-11e9-837d-dc12670456c9.png)

Which is a bit of a hassle when you've got big arrays of objects:
![image](https://user-images.githubusercontent.com/1940488/67061656-aa93e980-f1ac-11e9-9f6b-a93b25a436e3.png)
etc

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/180836762-57b6b32d-195e-4d65-bb73-e4c3ae73e0f4.png)
This is still happening for me

**Comment by qpwo** [comment]
Same for me sadly
