### ISSUE TITLE
Make README more clear

### ISSUE THREAD

**Issue by AshNaz87** [nodejs/repl#42]
Could you explain how to point `NODE_REPL_EXTERNAL_MODULE` to `which node-prototype-repl` ?

**Comment by devsnek** [comment]
That depends on the OS, you can just google "how to set environment variables on {insert os here}"

**Comment by AshNaz87** [comment]
I'm using Zsh on Mac OS.

I've added this to my `.zshrc` file:

`NODE_REPL_EXTERNAL_MODULE="$HOME/.nvm/versions/node/v12.11.1/bin/node-prototype-repl"`

and have run `source ~/.zshrc`. Still can't get it to work

**Comment by devsnek** [comment]
I can't really provide support for zsh, but if `echo $NODE_REPL_EXTERNAL_MODULE` works, then node should be able to pick it up.

**Comment by TipsyPixie** [comment]
@AshNaz87 
You're using v12.11.1 and Node 12 does not support `NODE_REPL_EXTERNAL_MODULE`. It works for >=13.3.0. Check this out.
https://github.com/nodejs/node/commit/c0305af2c4

**Comment by AshNaz87** [comment]
Will close now :)
