### ISSUE TITLE
Add support for await

### ISSUE THREAD

**Issue by zemse** [nodejs/repl#49]
This is a feature request to implement a similar existing feature In the chrome console on NodeJs REPL.

```
> asyncTaskThatResolvesNumber();
Promise<pending>

// chrome console
> await asyncTaskThatResolvesNumber();
123

// nodejs repl
> await asyncTaskThatResolvesNumber();
await asyncTaskThatResolvesNumber()
^^^^^

Uncaught:
SyntaxError: await is only valid in async functions and the top level bodies of modules
```

I think this can be very helpful for debugging or just quick trying out stuff. Current workaround I use is

```
> asyncTaskThatResolvesNumber().then(console.log)
```

**Comment by devsnek** [comment]
This repl already supports this. You can see the README for installation instructions.
