### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/repl#50]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

I don't see any references to the master branch so I don't think the rename will cause any issues.

Please let me know if you have any concerns by June 26th, otherwise I'll go ahead with the rename.

**Comment by mhdawson** [comment]
@devsnek FYI

**Comment by devsnek** [comment]
@mhdawson go for it.

**Comment by mhdawson** [comment]
@devsnek Hmm, there already seems to be a main branch do you you what that is?

**Comment by devsnek** [comment]
@mhdawson yeah i created that before realizing i don't have perms to change the default branch here.

**Comment by mhdawson** [comment]
Ok, I'll just delete and then rename

**Comment by mhdawson** [comment]
Renamed, closing
